### ISSUE TITLE
Feature Request: Color Blind Mode

### ISSUE THREAD

**Issue by Agentscreech** [Mikescher/GridDominance#1]
The default colors are on the darker side of things.  This makes it harder for people that are partially color blind to tell which dots are theirs.  I think if you just maxed the colors on them to be as bright as they could be and spread them out a bit it would be easier to see.

Suggestion is to have these 4 colors be enabled for people with deuteranomaly (red/green color blind)

Red = FF0000
Green = 00FF00
Blue = 0000FF
Yellow = FFFF00

I don't have enough C# or Android dev experience otherwise I'd do a pull request after I tested it.

**Comment by Mikescher** [comment]
The current player colors are 
 - #C0392B (red)
 - #2980B9 (blue)
 - #8E44AD (purple)
 - #F39C12 (orange)
 - #16A085 (greenish)

Do you have an idea for a fifth color so I can exchange them all (when in colorblind mode)?

**Comment by Agentscreech** [comment]
If you didn't want to go with a gray scale color (Black/white)

I would say the fifth color would be #00FFFF  I might think it's a gray scale or really light blue, but it's easy to separate it from the others.  Again, this is for red/green colorblindness.  You might have to get some input from some colorblind people with the more rare versions

**Comment by QuantumDancer** [comment]
Just making the colors brighter doens't help color blind people, since they have a hard time distinguishing different colors (most of the times red and green.)

Here's a color blind friendly color pallet:
http://jfly.iam.u-tokyo.ac.jp/color/#pallet
